== Angular CLI

=== CLI

| ng serve |

.Table
|===
|Command|Descrption

|ng serve | Build and run DevServer
|ng new | erstellt neues angular-project : use "-t -s" for inline "-g" for skip-git

|===

== Angular

=== DataBinding

Setzt keine werte, sondern verbindet properties

|===
|Beschreibung|Bsp| Beschreibung

|String interpolation| {{expression}}}            | html -> class-property
|Property Binding    | [property] ="expression"   | https://angular.io/guide/property-binding
|Event Binding       | (event)="method()" | https://angular.io/guide/event-binding
|Two-Way-Binding     | [(ngModel)]="data"   | hm.
|others              | ... | https://angular.io/guide/attribute-binding#injecting-attribute-values
|===

==== Bemerkungen : Event Binding.

.Html-File
[source,angular2html]
<input text="text" (input)="onUserInput($event)" />

$event ist special -- wird zur laufzeit zu der aktuellen Event-Instance

==== string interpolation

.Html-File
[source,angular2html]
<p>{{property}} is a string </p>
<p>{{id}} is convert to a string</p>
<p>{{func()}} is executed and the return-value is converted to a String</p>

.Ts-File
[source,js]
class component {
    property: string = "some value";
    id: number = 10;
    func() { return id; }
}

=== Model

Bindet ein Form-Element zu einier Component - Property

.Html-File
[source,angular2html]
<input type="text"  [(ngModel)]="propertyName" name="sdf" />

.Ts-File
[source,typescript]
export class AppComponent {
  title = 'first-app';
}

Benötigt FormsModule als Import : ( manuell, kommt nicht von Intelllij ) .app.module.ts

==== Import Forms

===== Fehlermeldung : "Can't bind to 'ngModel' since it isn't a known property of 'input'"

.Lösung1:
<input>Element hat kein "name"-Property

.Lösung2:
FormsModule import in app.modoule.ts fehlt

.Lösung3:
Reihenfolge der Import in app.module.ts:

1. BrowserModule
2. FormsModule
3. ReactiveFormsModule

[source]
import {FormsModule} from "@angular/forms";
...
imports: [
    ....
    FormsModule
]

=== Directives : ngIf / ngStyle

==== ngIf ( und else )

.html if
[source,angular2html]
<p *ngIf="condition">print if Condition isTrue</p>

.html if-with-else
[source,angular2html]
<p *ngIf="condition; else CustomName">print if Condition isTrue</p>
<ng-template #CustomName>
  <p>print if Condition isFalse</p>
</ng-template>

"else" sieht total merkwürdig aus ... gefällt mir so garnicht ./

==== ngStyle

... hm. mixing programming + styling .. hm. nicht gut.

.html
[source]
<p [ngStyle]="{'background-color':getColor()">text</p>

.ts
[source]
getColor() {
return "red";
}

==== ngClass

ha ... hier kommt ngClass :)

.html
[source]
<div [ngClass]="{alert:true, 'alert-success': this.alertIsOk, 'alert-danger': !this.alertIsOk}">{{alert}}</div>

PropertyBinding zu 'ngClass' setzt eine klasse.
Das Binding kann ein string, Array, oder eine Map ( object ) sein.
(https://angular.io/api/common/NgClass)

ngClass kann nur "hinzufügen" .. d.h. andere class-zuweisungen bleiben erhalten ( via Js/html)

==== ngFor

.html
[source]
<p *ngFor="let item of mylist">{{item}}</p>

Zugriff auf den Iterator-Index : ( siehe https://angular.io/api/common/NgForOf#local-variables für weitere lokale variablen )

.html
[source]
<p *ngFor="let item of myList; let index = index; let maxSize = count;">{{item}} with {{maxSize}}</p>
